name: PyInstaller Windows

on:
  push:
      branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python39 -m pip install --upgrade pip
        pip39 install -r requirements.txt
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile app/app.spec
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: Image Tools Windows
        path: dist/Image Tools.exe
